### PR TITLE
add us_06_MP

### PR DESCRIPTION
**Pull request by zubex84**

### CODE REVIEW

**Review by AshleyKucuk — APPROVED** [review]

**Review by Awa26 — COMMENTED** [review]
super!

**Comment by sundaydog1** [comment]
done

**Review by zubex84 — COMMENTED** [review]
ok

**Review by balfaro2 — APPROVED** [review]
looks good

**Comment by sundaydog1** [comment]
hi? i didnt approve

**Review by sundaydog1 — APPROVED** [review]
maybe now?

**Review by balfaro2 — COMMENTED** [review]
looks good

**Pull request merged**
